// src/features/article/components/ArticleMeta.tsx
import { Link } from 'react-router-dom';
import { Article } from '../../../models/article.model';
import { defaultImage } from '../../../utils/default-image';

interface ArticleMetaProps {
  article: Article;
  children?: React.ReactNode;
}

export default function ArticleMeta({ article, children }: ArticleMetaProps) {
  return (
    <div className="article-meta">
      <Link to={`/profile/${article.author.username}`}>
        <img src={defaultImage(article.author.image)} alt={article.author.username} />
      </Link>

      <div className="info">
        <Link className="author" to={`/profile/${article.author.username}`}>
          {article.author.username}
        </Link>
        <span className="date">{new Date(article.createdAt).toLocaleDateString('en-US', { dateStyle: 'long' })}</span>
      </div>

      {children}
    </div>
  );
}

// src/app/features/article/components/article-meta.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Article } from '../models/article.model';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { DefaultImagePipe } from '../../../shared/pipes/default-image.pipe';

@Component({
  selector: 'app-article-meta',
  template: `
    <div class="article-meta">
      <a [routerLink]="['/profile', article.author.username]">
        <img [src]="article.author.image | defaultImage" data-testid="article-meta-img" />
      </a>

      <div class="info">
        <a class="author" [routerLink]="['/profile', article.author.username]">
          {{ article.author.username }}
        </a>
        <span class="date">
          {{ article.createdAt | date: 'longDate' }}
        </span>
      </div>

      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, DatePipe, DefaultImagePipe],
})
export class ArticleMetaComponent {
  @Input() article!: Article;
}
